config/routes.rb
Rails.application.routes.draw do

  get root to: 'top#index'
  get "top/about" => "top#about"

  # accounts
  get 'accounts/:user_id' => 'accounts#edit'
  patch 'accounts/:user_id' => 'accounts#update'
  get 'accounts/:user_id/check' => 'accounts#check_delete'
  patch 'accounts/:user_id/delete' => 'accounts#delete'

  #announcemnt
  get '/announcements/index' => 'announcements#index'
  get '/announcements/new' => 'announcements#new'
  post '/announcements/create' => 'announcements#create'

  #book_mark
  post '/users/:user_id/works/:work_id/book_marks' => 'book_marks#create'
  delete '/users/:user_id/works/:work_id/book_marks' => 'book_marks#destroy'

  #faq
  get 'tags/:tag'=> 'faqs#index', as: :tag
  get 'faqs'          => 'faqs#index'
  get 'faqs/new'      => 'faqs#new'
  get 'faqs/:id'      => 'faqs#show'
  get 'faqs/:id/edit' => 'faqs#edit'
  post 'faqs'         => 'faqs#create'
  patch 'faqs/:id'    => 'faqs#update'
  delete 'faqs/:id'   => 'faqs#destroy'

  # moku
  get '/ajax/justnow' => 'mokus#justnow'
  post '/ajax/mokus/create' => 'mokus#ajax_create'
  patch '/mokus/:id/finish' => 'mokus#finish'

  get 'users/:user_id/mokus/:moku_id/check' => 'mokus#check_delete'
  patch 'users/:user_id/mokus/:moku_id/delete' => 'mokus#delete'


  #moku_type
  get 'users/:user_id/moku_type/:moku_type_id/check' => 'moku_type#check_delete'
  patch 'users/:user_id/moku_type/:moku_type_id/delete' => 'moku_type#delete'

  #mypage
  get 'mypage/:user_id/edit' => 'mypage#edit'
  get 'mypage/:user_id' => 'mypage#show'
  get 'mypage' => 'mypage#index'
  # ↑application_controllerのafter_sign_in_path_for(resource)メソッドでログイン後はここがデフォになってるからuser_idはなくても大丈夫
  patch 'mypage/:user_id' => 'mypage#update'

  #work
  get '/users/:user_id/mokus/:id/work/new' => 'work#new' #mokus→moku_idへ！
  post '/users/:user_id/mokus/:moku_id/work' => 'work#create'

  get 'users/:user_id/works/:work_id/check' => 'work#check_delete'
  patch 'users/:user_id/works/:work_id/delete' => 'work#delete'


  devise_for :users
  get 'users/:user_id/works/:work_id/public' => 'work#for_public'
  delete 'work/:id/images/:image_id' => 'work#delete_image'

  resources :users do
    resources :mokus, :moku_type, :work, :book_marks
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htmls
end

app/models/faq.rb
class Faq < ApplicationRecord
  belongs_to :user

  validates :questions, presence: true, uniqueness: true
  validates :answer, presence: true
  # validates :category, presence: true
  validates :user_id, presence: true

  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :categories
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController

  before_action :authenticate_user!, only:[:new, :create, :edit, :update, :destroy]
  before_action :ensure_admin_user, only: [:new, :create, :edit, :update, :destroy]

  def index
    if  params[:tag]
      @faqs = Faq.tagged_with(params[:tag])
    else
      @faqs = Faq.all
    end
  end

  def show
    @faq = Faq.find(params[:id])
  end

  def new
    @faq = Faq.new
    # @faqs = Faq.all
    @user = current_user

    # ↓これアクティブにすると、カテゴリ新規追加に反映されてselecteddに反映しなくなっちゃう
    # @faq.category = Constants::GENERAL
  end

  def create
    # user = User.find_by(id: current_user.id)

    @faq = Faq.new(faq_params)
      # questions: params[:faq][:questions],
      # answer: params[:faq][:answer],
      # category: params[:faq][:category],
      @faq.user_id = current_user.id

    if @faq.save
      flash[:notice] = "FAQを登録しました！"
      redirect_to(faqs_path)
    else
      render(faqs_new_path)
    end
  end

  def edit
    @faq = Faq.find_by(id: params[:id])
    @user = current_user
  end

  def update
    @faq = Faq.find(params[:id])
    @faq.update(faq_params)
    # @faq.questions = params[:faq][:questions]
    # @faq.answer = params[:faq][:answer]
    # @faq.category = params[:faq][:category]
    # user_id = current_user.id

    if @faq.save
      flash[:notice] = "FAQを更新しました！"
      redirect_to("/faqs/#{@faq.id}")
    else
      render action: :edit
    end
  end


  def destroy
    @faq = Faq.find_by(id: params[:id])
    @faq.destroy
    redirect_to(faqs_path)
  end

  private
  def ensure_admin_user
    user = current_user

    if user.admin == false
      flash[:notice] = "権限がありません"
      redirect_to(mypage_path)
    end

  end

  def faq_params
    params.require(:faq).permit(:id, :questions, :answer, :category_list) #, :user_id)
  end
end

app/helpers/faqs_helper.rb
module FaqsHelper

  # faqs = Faq.all

  # category = []
  # faqs.each do |faq|
  #   category << faq.category
  # end
  # category = faqs.map { faq.category }

end

app/views/faqs/edit.html.erb
<h1>Faq#edit</h1>

<%= form_with(model: @faq,
              url: {controller: :faqs, action: :update, id: @faq.id},
              method: :patch,
              local: true) do |form| %>

  <% if @faq.errors.any? %>
    <% @faq.errors.full_messages.each do |message| %>
      <%= message %><br>
    <% end %>
  <% end %><br>

  <p><%= form.text_area :questions %></p>
  <p><%= form.text_area :answer %></p>
  <%= form.label :category_list, "タグをカンマ区切りで入力" %>
  <%= text_field_tag 'faq[category_list]', @faq.category_list.join(',') %>
  <p><%= form.submit "更新する" %></p>
  <%= link_to("よくある質問一覧に戻る", faqs_path)%>
<% end %>

app/views/faqs/index.html.erb
<h1>Faqs#index</h1>
<h1>よくある質問</h1>
<h2>カテゴリ一覧</h2>
<div id="tag_cloud">
  <% tag_cloud Faq.category_counts, %w{s m l} do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div><br>

<% @faqs.each do |faq| %>
  <ul>
    <li>
      <h3><%= link_to(faq.questions, "/faqs/#{faq.id}") %></h3>
      <%#= faq.category_list %>
      <h6>カテゴリー：<%= raw faq.category_list.map { |t| link_to t, tag_path(t)}.join(',') %></h6>
    </li>
  </ul>
<% end %>




  <% if current_user %>
    <p><%= link_to("マイページへ戻る", "/mypage")%></p>
  <% else %>
    <p><%= link_to("TOPへ戻る", "/")%></p>
  <% end %>

app/views/faqs/new.html.erb
<h1>FQA#new</h1>

<%= form_with(model: @faq,
              url: {controller: :faqs, action: :create},
              method: :post,
              local: true) do |form| %>

  <% if @faq.errors.any? %>
    <% @faq.errors.full_messages.each do |message| %>
      <%= message %><br>
    <% end %>
  <% end %><br>

  <%= form.label :Q %>
  <p><%= form.text_area :questions %></p>

  <%= form.label :A %>
  <p><%= form.text_area :answer %></p>

  <%= form.label :category_list, "タグをカンマ区切りで入力" %>
  <%= text_field_tag 'faq[category_list]', @faq.category_list.join(','), "data-role" => "tagsinput" %>

  <p><%= form.submit "登録する" %></p>
<% end %>

<%= link_to("よくある質問一覧に戻る", faqs_path) %>
<h3><%= link_to("マイページへ戻る", "/mypage") %></h3>

app/views/faqs/show.html.erb
<h1>Faqs#show</h1>

<h3>カテゴリー</h3>
<%= raw @faq.category_list.map { |t| link_to t, tag_path(t)}.join(',') %>

<h1><%= simple_format(@faq.questions) %></h1>
<h3><%= simple_format(@faq.answer) %></h3>

<% if current_user %>
  <% user = User.find_by(id: current_user.id) %>
  <% if user.admin? %>
    <%= link_to("編集", "/faqs/#{@faq.id}/edit") %>
    <%= link_to("削除", "/faqs/#{@faq.id}", {method: :delete}) %>
  <% end %>
<% end %>

<p><%= link_to("よくある質問一覧に戻る", faqs_path)%></p>