config/routes.rb
Rails.application.routes.draw do

  get root to: 'top#index'
  get "top/about" => "top#about"

  # accounts
  get 'accounts/:user_id' => 'accounts#edit'
  patch 'accounts/:user_id' => 'accounts#update'
  get 'accounts/:user_id/check' => 'accounts#check_delete'
  patch 'accounts/:user_id/delete' => 'accounts#delete'

  #announcemnt
  get '/announcements/index' => 'announcements#index'
  get '/announcements/new' => 'announcements#new'
  post '/announcements/create' => 'announcements#create'

  #book_mark
  post '/users/:user_id/works/:work_id/book_marks' => 'book_marks#create'
  delete '/users/:user_id/works/:work_id/book_marks' => 'book_marks#destroy'

  #faq
  get 'tags/:tag'=> 'faqs#index', as: :tag
  get 'faqs'          => 'faqs#index'
  get 'faqs/new'      => 'faqs#new'
  get 'faqs/:id'      => 'faqs#show'
  get 'faqs/:id/edit' => 'faqs#edit'
  post 'faqs'         => 'faqs#create'
  patch 'faqs/:id'    => 'faqs#update'
  delete 'faqs/:id'   => 'faqs#destroy'

  # moku
  get '/ajax/justnow' => 'mokus#justnow'
  post '/ajax/mokus/create' => 'mokus#ajax_create'
  patch '/mokus/:id/finish' => 'mokus#finish'

  get 'users/:user_id/mokus/:moku_id/check' => 'mokus#check_delete'
  patch 'users/:user_id/mokus/:moku_id/delete' => 'mokus#delete'


  #moku_type
  get 'users/:user_id/moku_type/:moku_type_id/check' => 'moku_type#check_delete'
  patch 'users/:user_id/moku_type/:moku_type_id/delete' => 'moku_type#delete'

  #mypage
  get 'mypage/:user_id/edit' => 'mypage#edit'
  get 'mypage/:user_id' => 'mypage#show'
  get 'mypage' => 'mypage#index'
  # ↑application_controllerのafter_sign_in_path_for(resource)メソッドでログイン後はここがデフォになってるからuser_idはなくても大丈夫
  patch 'mypage/:user_id' => 'mypage#update'

  #work
  get '/users/:user_id/mokus/:id/work/new' => 'work#new' #mokus→moku_idへ！
  post '/users/:user_id/mokus/:moku_id/work' => 'work#create'

  get 'users/:user_id/works/:work_id/check' => 'work#check_delete'
  patch 'users/:user_id/works/:work_id/delete' => 'work#delete'


  devise_for :users
  get 'users/:user_id/works/:work_id/public' => 'work#for_public'
  delete 'work/:id/images/:image_id' => 'work#delete_image'

  resources :users do
    resources :mokus, :moku_type, :work, :book_marks
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htmls
end

app/models/moku.rb
class Moku < ApplicationRecord
  belongs_to :user
  belongs_to :moku_type
  has_many :works
  has_many :stamps　#使わない

  #create時からずっと
  validates :user_id, presence: true
  validates :moku_type_id, presence: true
  validates :mjn_public, inclusion: { in: [true, false] }
  validates :started_at, presence: true

  #update == MOKU終了時以降
  validates :finished_at, presence: true, on: :update
  validates :moku_time, presence: true, on: :update

  def format_created_at
    self.created_at.strftime('%y/%m/%d  %H:%M')
  end
end

app/models/moku_type.rb
class MokuType < ApplicationRecord
  belongs_to :user
  has_many :mokus

  validates :name, presence: true
  validates :user_id, presence: true
end

app/controllers/mokus_controller.rb
class MokusController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, only:[:index, :show, :new, :create, :edit, :update]
  skip_before_action :verify_authenticity_token, only:[:ajax_create]

  # reqire 'ruby-duration' なんか間違ってる。

  def index
    # 絞り込み用を書く
    if params[:moku_type]
      @user = current_user
      # @moku_type = MokuType.where(id: params[:id])
      @mokus = Moku.where(user_id: current_user.id).where(moku_type_id: params[:moku_type]).where(deleted: false).order(created_at: 'desc')
    else
      @user = current_user
      @mokus = Moku.where(user_id: @user.id).where(deleted: false).order(created_at: 'desc')
    end
  end

  def show
    @user = current_user
    @moku = Moku.find(params[:id])
    @moku_type = MokuType.find(@moku.moku_type_id)
    @works = Work.where(moku_id: @moku.id)
    # @time = Time.at(@moku.moku_time) 意図した結果通り出ないから×
    # time = Duration.new(@moku.moku_time) エラー出たのであとで確認
    # @moku_time = time.format(%H:&M:%S)
  end

  def new
    @user = current_user
    @moku_types = MokuType.where(user_id: @user.id)
  end

  # def create
  #   @moku = Moku.new(
  #     user_id: current_user.id,
  #     moku_type_id: params[:moku_type],
  #     mjn_public: params[:mjn_public],
  #   )

  #   if @moku.save
  #     flash[:notice] = "MOKU開始！頑張って！"
  #     redirect_to(mypage_path)
  #   else
  #     render action: :new
  #   end
  # end

  def ajax_create
    moku = Moku.new
    moku.user_id = params[:user_id]
    moku.moku_type_id = params[:moku_type_id]
    moku.mjn_public = params[:mjn_public]
    moku.started_at = DateTime.now

    if moku.save!
      render json: moku
    else
      render :new
    end
  end

  def finish
    moku = Moku.find params[:id]
    moku.finished_at = DateTime.now
    moku.moku_time = params[:moku_time]

    moku.save!
    flash[:notice] = "おつかれさまでした！"
    redirect_to("/mypage")
  end

  def edit
    @user = current_user
    @moku = Moku.find(params[:id])
    # @moku_type = MokuType.find_by(id: @moku.moku_type_id)
    # @works = Work.where(moku_id: @moku.id)
  end

  def update
    user = current_user
    @moku = Moku.find(params[:id])
    @moku.content = params[:moku][:content]
    # @moku.mjn_public = params[:moku][:mjn_public] →開始時にしか拾わないからupdateでは必要ない

    moku_type = MokuType.find(params[:moku][:moku_type])
    @moku.moku_type = moku_type

    if @moku.save!
      flash[:notice] = "更新しました！"
    else
      render action: :edit
    end

    redirect_to action: :show, user_id: user.id, id: @moku.id
  end

  def check_delete
    @moku = Moku.find(params[:moku_id])
    @works = Work.where(moku_id: @moku.id)
  end

  def delete
    moku = Moku.find(params[:moku_id])
    moku.deleted = true
    moku.save!

    works = Work.where(moku_id: moku.id)
    works.each do |work|
      work.deleted = true
      work.save!

      book_marks = BookMark.where(work_id: work.id)
      book_marks.each do |book_mark|
        book_mark.deleted = true
        book_mark.save!
      end
    end

    flash[:notice] = "MOKUを削除しました☁︎"
    redirect_to(user_mokus_path)
  end

  def justnow
    mokus = Moku.where(mjn_public: true).where(deleted: false).order(created_at: 'desc').limit(5) # 最新を先に表示するから、desc
    render json: mokus, include:[:user, :moku_type], methods: [:format_created_at]#これでmokusがjson(≒JSのハッシュ)になる。さらになぜかuserモデルとmoku_typeモデルが拾える。
  end
end

app/helpers/mokus_helper.rb
module MokusHelper

    # apprication_helperにかいた、公開非公開の選択肢をまねてmokus#newのMJNの選択肢
    # 元の部分はlib/constants.rbにいる
  def options_for_mjn
      Constants.options_for_mjn
  end

  def format_moku_time
    hours = moku_time / (60 * 60)
    minutes = moku_time / 60.floor
    seconds = moku_time
    return "#{hours}時間　#{minutes}分 #{seconds}秒"
  end
end

app/views/mokus/_moku_js.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.js"></script>
<script>
    //ブラウザバックや再読み込みする時に確認メッセージを出すためのフラグ
    //MOKU開始前は戻れないと困るから。
    let nowStarted = false;

    // ストップウォッチ関係の変数　とりあえずお手本のまま。あとで調整
    let timeCounter = 0; //数値がインクリメントされるため０で初期化
    let timer = null; //setIntervalの処理結果を代入するから初期化
    let startTime = null; //Dateからのデーターが入るので0ではなくnullで初期化
    let endTime = null;

    let time;
    let hour = document.getElementById("hour");
    let minute = document.getElementById("minute");
    let second = document.getElementById("second");

    function startClock() {
      time = new Date();

      hour.style.transform = "rotate("+(time.getHours()*30+time.getMinutes()*0.5)+"deg)";
      minute.style.transform = "rotate("+(time.getMinutes()*6)+"deg)";
      second.style.transform = "rotate("+(time.getSeconds()*6)+"deg)";

      setTimeout(startClock, 1000-time.getMilliseconds());
    }

    function displayTimer() { //displayTimerという関数宣言
        timeCounter = ++timeCounter // 変数timeCounterが＋１　++が前にあると出力してから加算、後にあれば加算してから出力
        // $("#timer").text(timeCounter) // #timer === id="timer" に変数timeCounterを表示させる。text=マッチした要素内のテキストを取得する。つまりtimeCounterの値を#timerに表示しているという。
        let duration = moment.duration(timeCounter, 'seconds')
            formatDuration = moment.utc(duration.as('milliseconds')).format('HH:mm:ss')
            $("#timer").text(formatDuration)
            $('#mokuTime').val(timeCounter)
            // console.log(Time.at(timeCounter).utc.strftime('%X'))
            // console.log(moment.duration(timeCounter).format('hh:mm:ss'))
            // console.log(formatDuration)
            // moment.utc(duration.as('milliseconds')).format('HH:mm:ss')
    }

    $(document).ready(function () {
        $(window).on('beforeunload', function () {
            if (nowStarted) {
                return "ちょっとまって"
            }
        })
        startClock();

        $('#startButton').on('click', function () {
            nowStarted = true　//MOKU中はブラウザバック・再読み込み時にalertを出すためそのフラグ変更
            $.ajax({
                url: '/ajax/mokus/create', //ajyaxでデーター送る時のURL(routes参照)
                method: 'post', //リクエストメソッド
                data: {
                    user_id: <%= current_user.id %>, //create時に欲しいデーターの皆さん
                    moku_type_id: $('#moku_type').val(),
                    mjn_public: $('#mjn_public').val(),
                    // authenticity_token: $('meta[name="csrf-token"]').attr('content')
                }
            }).done(function (json) { //↑までうまくいったら json === mokus_controllerでrender json: moku　したもの。ajax_createしたMOKUのデータが入ってくる
                const moku = json //ajax_createしたmokuのデーターをJSの定数mokuへ代入
                const mokuId = moku.id //定数mokuIdの定義
                $('#startedMokuId').val(mokuId) //id='startedMokuIdの値に定数mokuIdの値を代入してJSでもmoku.idが使えるよう保持'

                const url = '/mokus/' + mokuId + '/finish' //定数urlを定義　これを使って、終了時のデーター飛び先URLを組み立てる
                $('#finishForm').attr('action', url) //form_withのid: 'finishForm'の内容をurlに書き換える？？？？
                $('#clockImage').fadeIn(2000) //時計をフェードイン
                $('#afterStartTitle, #stopButton, #pauseButton').show() //開始後のタイトルとストップボタンを表示
                $('#greet, #defaultTitle, #startButton, #moku_type, #mjn_public, #selectMokuType, #selectMJN, #linkToMypage, #linkToAaacount, #linkToSetting, #linkToLogout, #linkToTaq').hide() //開始後のデフォタイトルやタートボタンなどを非表示

                // ここから開始時のタイマーの作業
                timer = setInterval(displayTimer, 1000) //タイマーの開始はもっと上の方がいいのかな
                  if (startTime == null) { //変数startTimeがnullのときだけその時の日時を入れる。
                  startTime = new Date() //スタートを再クリックすると開始時刻が更新されてしまうのを防ぐため。DBには保存しないが制御上多分必要。
                  $('#startTimeInput').val(startTime) //DBへは必要ないけどカウント的に必要なきがする
                }
               })
               })

                // ここから終了時のタイマーの作業
                $('#stopButton').on('click', function () { //【処理２】stopButton要素がクリックされたら、このfunction以下を処理するよ
                  endTime = new Date() //変数endTimeに今の日時を代入
                  $('#endTimeInput').val(endTime) //DBには保存しないが制御上多分必要。
                  // $('#mokuTime').val(timeCounter) //全部で何分MOKUったか。
                    nowStarted = false;
                  clearInterval(timer) //setIntervalでセットしたタイマーをクリア
                  timeCounter = 0 //timeCounterを０に戻して経過秒数を０にする
                })

            //ここから一時停止のタイマーの作業
                $('#pauseButton').on('click', function () {
                  if (nowStarted) {
                    clearInterval(timer); //setInterbalでセットしたタイマーをクリア。displayTimerではなく値が代入されているtimerを指定する。
                    $('#pauseButton').val('再開！');
                    nowStarted = false;
                  } else {
                    $('#pauseButton').val('一時停止！');
                    nowStarted = true;
                    timer = setInterval(displayTimer, 1000);
                  };
                 })
    })
</script>

app/views/mokus/check_delete.html.erb
<h1>mokus#check_delete</h1>

<h1>MOKUを削除するときはご注意ください</h1>
<ul>
  <li>MOKUを削除すると、このMOKUの【成果物】も全て消えてしまいます。</li>
  <li>Book Markされていた成果物の場合、Book Markからも消えてしまいます。</li>
  <li>一度削除すると、復活することはできません。</li>
</ul>

<h3>このMOKUの成果物一覧</h3>
<% if @works.any? %>
  <% @works.each do |work| %>
    <p>成果物のタイトル：<%= link_to("#{work.title}", "/users/#{work.user_id}/work/#{work.id}") %></p>
  <% end %>
<% else %>
  <h2>このMOKUには成果物の登録がありませんでした。</h2>
<% end %>

<h3>本当にこのMOKUを削除してよろしいければ、削除ボタンをクリックしてください。</h3>

<%= form_with(model: @moku,
              url: {controller: :mokus, action: :delete, user_id: current_user.id, moku_id:@moku.id},
              method: :patch,
              local: true) do |f| %>

<%= f.submit "MOKUを削除する" %>

<% end %>

app/views/mokus/edit.html.erb
<h1>mokusコントローラの　editビュー</h1>

<h2><%= "#{@user.name}さんが#{@moku.created_at}にMOKUった内容" %></h2>



<%= form_with(model: @moku,
              url: {controller: :mokus, action: :update, user_id: @user.id, id: @moku.id},
              method: :patch,
              local: true) do |form| %>
  <!--  https://qiita.com/colorrabbit/items/b58888506e41d1370fd1-->
  <% if @moku.errors.any? %>
    <% @moku.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>

  <h4>MOKUタグ</h4>
    <%= form.collection_select :moku_type, @user.moku_types, :id, :name, selected: @moku.moku_type_id %>
  <%# form.collection_select :対象のカラム名,プルダウンに表示するデータの配列, :データー格納先カラム名, :データー格納先カラム名, selected: そのmokuのmoku_type_idを拾ってそれに該当するMOKUタグを表示しておく%>

  <h4>やったことやめも</h4>
  <%= form.text_area :content %>

  <%
=begin%>
MOKU開始の時しかMJNに拾われないから編集不要。
 <h4>MOKU JUST NOWへの公開設定</h4>
<%= form.select :mjn_public, options_for_public_for_bool, selected: @moku.mjn_public %></h4>
<%
=end%>

<p><%= form.submit '保存' %></p>

<% end %>
　
<%= link_to("MOKUった一覧へ戻る", user_mokus_path(@user))%>
<%= link_to("マイページへ戻る", "/mypage")%>

app/views/mokus/index.html.erb
<h1>Mokus#index</h1>
<h1><%= "#{@user.name}さんのMOKUった一覧" %></h1>

<% if true %>
 <%= form_with(model: @moku,
              url: {controller: :mokus, action: :index, user_id: current_user.id, moku_type: @user.moku_types.ids},
              method: :get, #明示的にgetの追記が必要だった
              local: true) do |form| %>

    <h4>絞り込み</h4>
    <%= form.collection_select :moku_type, @user.active_moku_types, :id, :name, selected: @user.moku_types %>
    <%= form.submit "絞り込む" %>
  <% end %>
<% end %>

  <% @mokus.each do |moku| %>
    <ul>
      <li>
        <p><%= link_to("#{moku.created_at} の MOKU", user_moku_path(moku.user_id, moku.id)) %>
        <% moku_type = MokuType.find(moku.moku_type_id) %>
        <%= "MOKUタグ：#{moku_type.name}" %>
        <%= link_to("【MOKUを削除する】","/users/#{moku.user_id}/mokus/#{moku.id}/check")%>
        <%= link_to("【成果物の登録】", "/users/#{moku.user_id}/mokus/#{moku.id}/work/new") %></p>
      </li>
    </ul>
  <% end %>

  <h5>----- 絞り込み　-----</h5>
    <% moku_types = MokuType.where(user_id: current_user.id).where(deleted: false) %>
    <% moku_types.each do |moku_type| %>
    <p><%= link_to moku_type.name, "/users/#{current_user.id}/mokus?moku_type=#{moku_type.id}" %></p>
  <% end %>


<%#= link_to(" Rubyでしぼりこみ", "/users/#{current_user.id}/mokus?moku_type=3")%>
<%# end %>
<h5><%= link_to("全ての一覧", user_mokus_path(@user)) %></h5>
<h5>------------------------</h5>
<h4><%= link_to("マイページへ戻る", "/mypage") %></h4>

app/views/mokus/new.html.erb
<h1>Moku#new</h1>
<html>
<head>
  <style>
    #clockImage {
        width: 300px;
        height: 300px;
              position: relative;
      }
      .clock {
        width: 300px;
        height: 300px;
        position: absolute;
        top: 0px;
        left: 0px;
      }
  </style>
</head>
<body>
  <span id="defaultTitle"><h1>MOKUる</h1></span>
    <span id="afterStartTitle" style="display:none;"><h1>ただいまMOKUっています！</h1></span>
    <%# <span id="afterStartTitle" style="display:none;"><h4>終了するときは【MOKU終了！】をクリック！</h4></span> これいらなかった%>
    <div id="clockImage" style="display:none;">
        <img src="/assets/dial.png" class="clock"><!--文字盤-->
        <img src="/assets/hour.png" id="hour" class="clock"><!--短針-->
        <img src="/assets/minute.png" id="minute" class="clock"><!--長針-->
        <img src="/assets/second.png" id="second" class="clock"><!--秒針-->
    </div>


  <%= form_with(model: @moku,
                url: {controller: :mokus, action: :create, user_id: current_user.id},
                method: :post, #getでもいけるけれど設計的に美しくないのでやはりpostがいい
                local: true) do |form| %>

    <%# if @moku.errors.any? %>
      <%# @moku.errors.full_messages.each do |message| %>
        <%#= message %><br>
      <%# end %>
    <%# end %>

  <span id="selectMokuType"><h3>なにをMOKUりますか？MOKUタグを教えてください</h3></span>
  <%= form.collection_select :moku_type, @user.active_moku_types, :id, :name, selected: @user.moku_types %>
    <%# form.collection_selectのメモ
    :moku_type...指定したモデル@mokuのどのカラムが対処？
    @user.moku_type...選択肢になるデーター。@user（そのユーザー）が持ってるmoku_type全部対象だかからmoku_types（っていうかmoku_typesテーブルだなこれ多分）
    :id...表示している選択肢のmoku_typeのid。多分前段でmoku_typesテーブル指定してて、だからidだけでmoku_type.idが拾えてる。これparamsで拾われる。
    :name...表示するmoku_typeのなまえ。これもmoku_typesテーブル参照されてて、moku_typeのなまえはnameにしたから取れるんだ。
    selected:...オプション。どの選択肢を表示しておくか。editならcreate時のデーター引っ張ってる。newの時はHTML的に最初に書かれてるものが出る。
    %>

<%# MKNへ公開されても何も不利益が出ない。mokuトモ作らなくなったから。無しにする。問答無用で載せる%>
  <span id="selectMJN"><h3>MOKU JUST NOWに公開していいですか？</h3></span>
  <%= form.select :mjn_public, options_for_public_for_bool %>

<% end %>

<hr/>
<input type="hidden" id="startedMokuId"/> <%#= create後に発行されたmoku.idの保存 %>
<span id="timer"></span>
<%# ↑本番含め開発中はtextにしてるけど、運用開始時はimputにしてhiddenで隠す。もしくは６０で割って算数＋分表示に%>


<%# displayTimerでインクリメントにより何秒経過したのか計算された結果を表示している %>
<button type="button" id="startButton">MOKU開始！</button>
<input type="submit" id="pauseButton" style="display:none;" value="一時停止！"/>

<%= form_with(url: 'dummy', method: :patch, local: true, id: 'finishForm') do |form| %> <%# id: はid=と同じ　この中に書いたものをfinish時に一緒に送ってあげる%>
  <input type="hidden" name="moku_time" id="mokuTime" value=""/> <%# MOKUった時間の総合計を保存 %>
  <input type="submit" id="stopButton" style="display:none;" value="MOKU終了！"/>
<% end %>

<h3 id="linkToMypage"><%= link_to("マイページへ戻る", "/mypage")%></h3>

<%= render 'shared/to_mypage'%>
<%= render 'moku_js' %>

</body>
</html>

app/views/mokus/show.html.erb
<h1>mokusコントローラの　showビュー</h1>

<h1><%= "#{@user.name}さんが#{@moku.created_at}にMOKUった内容"%></h1>

<h4>MOKU 終了時刻</h4>
<%= @moku.updated_at %>

<h4>MOKU TIME</h4>
<%= "#{distance_of_time_in_words(@moku.moku_time)}MOKUりました！" %>

<h4>MOKUタグ</h4>
<%= @moku_type.name%>

<h4>やったことやめも</h4>
<h4><%= simple_format(@moku.content) %></h4>


<h4><%= "このMOKUの成果物一覧" %></h4>
<% if @works %>
  <% @works.each do |work| %>
  <ul>
    <li>
      <%= link_to(work.title, user_work_path(work.user_id, work.id)) %>
    </li>
  </ul>
  <% end %>
<% end %>

<h4><%= "MOKU JUST NOWへの公開設定は、#{public_to_s(@moku.mjn_public)} でMOKUりました" %></h4>

<p><%= link_to("【編集】", edit_user_moku_path(@user, @moku.id)) %></p>
<%= link_to("MOKUった一覧へ戻る", user_mokus_path(@user))%>
<h3><%= link_to("マイページへ戻る", "/mypage")%></h3>