config/routes.rb
Rails.application.routes.draw do

  get root to: 'top#index'
  get "top/about" => "top#about"

  # accounts
  get 'accounts/:user_id' => 'accounts#edit'
  patch 'accounts/:user_id' => 'accounts#update'
  get 'accounts/:user_id/check' => 'accounts#check_delete'
  patch 'accounts/:user_id/delete' => 'accounts#delete'

  #announcemnt
  get '/announcements/index' => 'announcements#index'
  get '/announcements/new' => 'announcements#new'
  post '/announcements/create' => 'announcements#create'

  #book_mark
  post '/users/:user_id/works/:work_id/book_marks' => 'book_marks#create'
  delete '/users/:user_id/works/:work_id/book_marks' => 'book_marks#destroy'

  #faq
  get 'tags/:tag'=> 'faqs#index', as: :tag
  get 'faqs'          => 'faqs#index'
  get 'faqs/new'      => 'faqs#new'
  get 'faqs/:id'      => 'faqs#show'
  get 'faqs/:id/edit' => 'faqs#edit'
  post 'faqs'         => 'faqs#create'
  patch 'faqs/:id'    => 'faqs#update'
  delete 'faqs/:id'   => 'faqs#destroy'

  # moku
  get '/ajax/justnow' => 'mokus#justnow'
  post '/ajax/mokus/create' => 'mokus#ajax_create'
  patch '/mokus/:id/finish' => 'mokus#finish'

  get 'users/:user_id/mokus/:moku_id/check' => 'mokus#check_delete'
  patch 'users/:user_id/mokus/:moku_id/delete' => 'mokus#delete'


  #moku_type
  get 'users/:user_id/moku_type/:moku_type_id/check' => 'moku_type#check_delete'
  patch 'users/:user_id/moku_type/:moku_type_id/delete' => 'moku_type#delete'

  #mypage
  get 'mypage/:user_id/edit' => 'mypage#edit'
  get 'mypage/:user_id' => 'mypage#show'
  get 'mypage' => 'mypage#index'
  # ↑application_controllerのafter_sign_in_path_for(resource)メソッドでログイン後はここがデフォになってるからuser_idはなくても大丈夫
  patch 'mypage/:user_id' => 'mypage#update'

  #work
  get '/users/:user_id/mokus/:id/work/new' => 'work#new' #mokus→moku_idへ！
  post '/users/:user_id/mokus/:moku_id/work' => 'work#create'

  get 'users/:user_id/works/:work_id/check' => 'work#check_delete'
  patch 'users/:user_id/works/:work_id/delete' => 'work#delete'


  devise_for :users
  get 'users/:user_id/works/:work_id/public' => 'work#for_public'
  delete 'work/:id/images/:image_id' => 'work#delete_image'

  resources :users do
    resources :mokus, :moku_type, :work, :book_marks
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htmls
end

app/controllers/moku_type_controller.rb
class MokuTypeController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user

  def index
    @user = current_user
    @moku_types = MokuType.where(user_id: @user.id).where(deleted: false)
  end

  def show
    @moku_type = MokuType.find(params[:id])
    @mokus = Moku.where(moku_type_id: @moku_type.id)
  end

  def new
    @user = current_user
    @moku_type = MokuType.new
  end

  def create
    @user = current_user

    @moku_type = MokuType.new(
      name: params[:name],
      user_id: params[:user_id],
    )
    if @moku_type.save
      flash[:notice] = "新しいMOKUタグを登しました！"
      redirect_to(user_moku_type_index_path(@user))
    else
      render action: :new
    end
  end

  def edit
    @moku_types = MokuType.where(user_id: current_user.id)
    @moku_type = MokuType.find(params[:id])
  end

 def update
    @moku_types = MokuType.where(user_id: current_user.id) #これがないとrender時にeachがnilだと言われる
    @moku_type = MokuType.find(params[:id])
    @moku_type.name = params[:moku_type][:name]
    @moku_type.user_id = current_user.id

    if @moku_type.save
      flash[:notice] = "更新しました！"
      redirect_to(user_moku_type_index_path(@user))
    else
      render :edit
      # redirect_to(edit_user_moku_type_path(current_user.id, @moku_type))
      # render plain:"OK"
    end
  end

  def check_delete
    @moku_type = MokuType.find(params[:moku_type_id])
    @mokus = Moku.where(moku_type_id: @moku_type.id)
  end

  def delete
    moku_type = MokuType.find(params[:moku_type_id])
    default_moku_type = MokuType.find_by(
      user_id: moku_type.user_id,
      name: Constants::DEFAULT_MOKU_TYPE_NAME)
    moku_type.deleted = true
    moku_type.save!

    mokus = Moku.where(moku_type_id: moku_type.id)
    mokus.each do |moku|
      moku.moku_type_id = default_moku_type.id
      moku.save!
    end

    flash[:notice] = "MOKUタグを削除しました☁︎"
    redirect_to(user_moku_type_index_path(moku_type.user_id))
  end

end

app/helpers/moku_type_helper.rb
module MokuTypeHelper
end

app/views/moku_type/_form.html.erb
<p><%= f.text_field :name %></p>
<%= f.submit "登録する" %>

<h3>今あるMOKUタグはこちら</h3>
<% @moku_types = MokuType.where(user_id: current_user.id) %>
<% @moku_types.each do |moku_type| %>
  <ul>
    <li>
      <%= moku_type.name %>
    </li>
  </ul>
<% end %>

app/views/moku_type/check_delete.html.erb
<h1>moku_type#check_delete</h1>

<h1>MOKUタグを削除するときはご注意ください</h1>

MOKUタグは、MOKUの管理に使われています。<br>
そのため、この<%= "【#{@moku_type.name}】" %>が削除されると<br>
<%= "【#{@moku_type.name}】" %>がつけられていたMOKUは<br>
自動的に【とりあえずMOKUる】のMOKUタグがつけられます。<br>

<h3><%= "#{@moku_type.name}のMOKUタグがつけられているMOKU" %></h3>
<% @mokus.each do |moku| %>
  <p><%= link_to("#{moku.format_created_at}のMOKU", "/users/#{moku.user_id}/mokus/#{moku.id}") %></p>
<% end %>

<h3>本当にこのMOKUタグを削除してよろしければ、削除ボタンをクリックしてください。</h3>
<%= form_with(model: @moku_type,
              url: {controller: :moku_type, action: :delete, user_id: current_user.id, moku_type_id:@moku_type.id},
              method: :patch,
              local: true) do |f| %>

<%= f.submit "MOKUタグを削除する" %>

<% end %>

app/views/moku_type/edit.html.erb
<h1>Moku_type#edit</h1>
<h1>MOKUタグの編集</h1>

<%= form_with(model: @moku_type,
url: {controller: :moku_type, action: :update, user_id: current_user.id, id: @moku_type},
method: :patch,
local: true) do |f| %>

  <% if @moku_type.errors.any? %>
    <% @moku_type.errors.full_messages.each do |message| %>
      <%= message %><br>
    <% end %>
  <% end %>

  <%= "MOKUタグの新しい名前を教えてください" %>
  <%= render "form", f:f %>
<% end %>

<p><%= link_to("MOKUタグ一覧へ戻る", user_moku_type_index_path(@user))%></p>
<p><%= link_to("マイページへ戻る", "/mypage")%></p>

app/views/moku_type/index.html.erb
<h1>MokuType#index</h1>
<h1><%= "#{@user.name}さんのMOKUタグ一覧"%></h1>
<h3>★「とりあえずMOKUる」は編集・削除できません★</h3>
<ul>
  <% @moku_types.each do |moku_type| %>
  <li>
    <%= moku_type.name %>
      <% if moku_type.name == Constants::DEFAULT_MOKU_TYPE_NAME %>
        <%= link_to("【MOKUったもの一覧】", user_moku_type_path(moku_type.user_id, moku_type.id)) %>
      <% else %>
        <%= link_to("【MOKUったもの一覧】", user_moku_type_path(moku_type.user_id, moku_type.id)) %>
        <%= link_to("【編集】", edit_user_moku_type_path(moku_type.user_id, moku_type.id))%>
        <%= link_to("【削除】", "/users/#{moku_type.user_id}/moku_type/#{moku_type.id}/check")%>
      <% end %>
    </li>
  <% end %>
</ul>
<p><%= link_to("新しいMOKUタグを追加する", new_user_moku_type_path(@user))%></p>
<p><%= link_to("マイページへ戻る", "/mypage")%></p>

app/views/moku_type/new.html.erb
<h1>Moku_type#new</h1>
<h1>あたらしいMOKUタグを追加</h1>

<%= form_with(model: @MokuType,
url: {controller: :moku_type, action: :create, user_id: current_user.id},
method: :post,
local: true) do |f| %>

<% if @moku_type.errors.any? %>
  <% @moku_type.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<h3>新しいMOKUタグの名前を教えてください</h3>

<%= render 'form', f:f %>
<% end %>

<%
=begin f.text_field :name %>
<%= f.submit "追加する" %>
<% end %>

<h3>今あるMOKUタグはこちら</h3>
<% @moku_types.each do |moku_type| %>
<ul>
  <li>
    <%= moku_type.name %>
  </li>
</ul>
<%
=end %>


<p><%= link_to("MOKUタグ一覧へ戻る", user_moku_type_index_path(@user))%></p>
<p><%= link_to("マイページへ戻る", "/mypage")%></p>

app/views/moku_type/show.html.erb
<h1>MokuType#show</h1>
<h1><%= "【MOKUタグ：#{@moku_type.name}】でMOKUったもの" %></h1>
<% @mokus.each do |moku| %>
<ul>
  <li>
    <%= link_to("#{moku.created_at}のMOKU", user_moku_path(moku.user_id, moku.id)) %>
  </li>
</ul>
<% end %>

<p><%= link_to("マイページへ戻る", "/mypage")%></p>