config/routes.rb
Rails.application.routes.draw do

  get root to: 'top#index'
  get "top/about" => "top#about"

  # accounts
  get 'accounts/:user_id' => 'accounts#edit'
  patch 'accounts/:user_id' => 'accounts#update'
  get 'accounts/:user_id/check' => 'accounts#check_delete'
  patch 'accounts/:user_id/delete' => 'accounts#delete'

  #announcemnt
  get '/announcements/index' => 'announcements#index'
  get '/announcements/new' => 'announcements#new'
  post '/announcements/create' => 'announcements#create'

  #book_mark
  post '/users/:user_id/works/:work_id/book_marks' => 'book_marks#create'
  delete '/users/:user_id/works/:work_id/book_marks' => 'book_marks#destroy'

  #faq
  get 'tags/:tag'=> 'faqs#index', as: :tag
  get 'faqs'          => 'faqs#index'
  get 'faqs/new'      => 'faqs#new'
  get 'faqs/:id'      => 'faqs#show'
  get 'faqs/:id/edit' => 'faqs#edit'
  post 'faqs'         => 'faqs#create'
  patch 'faqs/:id'    => 'faqs#update'
  delete 'faqs/:id'   => 'faqs#destroy'

  # moku
  get '/ajax/justnow' => 'mokus#justnow'
  post '/ajax/mokus/create' => 'mokus#ajax_create'
  patch '/mokus/:id/finish' => 'mokus#finish'

  get 'users/:user_id/mokus/:moku_id/check' => 'mokus#check_delete'
  patch 'users/:user_id/mokus/:moku_id/delete' => 'mokus#delete'


  #moku_type
  get 'users/:user_id/moku_type/:moku_type_id/check' => 'moku_type#check_delete'
  patch 'users/:user_id/moku_type/:moku_type_id/delete' => 'moku_type#delete'

  #mypage
  get 'mypage/:user_id/edit' => 'mypage#edit'
  get 'mypage/:user_id' => 'mypage#show'
  get 'mypage' => 'mypage#index'
  # ↑application_controllerのafter_sign_in_path_for(resource)メソッドでログイン後はここがデフォになってるからuser_idはなくても大丈夫
  patch 'mypage/:user_id' => 'mypage#update'

  #work
  get '/users/:user_id/mokus/:id/work/new' => 'work#new' #mokus→moku_idへ！
  post '/users/:user_id/mokus/:moku_id/work' => 'work#create'

  get 'users/:user_id/works/:work_id/check' => 'work#check_delete'
  patch 'users/:user_id/works/:work_id/delete' => 'work#delete'


  devise_for :users
  get 'users/:user_id/works/:work_id/public' => 'work#for_public'
  delete 'work/:id/images/:image_id' => 'work#delete_image'

  resources :users do
    resources :mokus, :moku_type, :work, :book_marks
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htmls
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController

  before_action :authenticate_user!
  # before_action :ensure_current_user, only:[:index]

  def index
    @user = current_user
    # @works_random = Work.where(pick_up: true).order("RANDOM()").limit(3)
    @work_randoms = Work.where(pick_up: true).where(deleted: false).order(created_at: 'desc').limit(3) #このままだと上から３つ固定なのでちょと考える
    @mokus = Moku.where(user_id: current_user.id).where(deleted: false) #カレンダーのために取得

    @annouce = Announcement.all
  end

  #↓current_userにしてはいけない。pick upで成果物の作者を見にくる場合もアクセスされるから。
  def show
    @user = User.find(params[:user_id])
  end

  # edit/updateはaccounts_controllerでの仕事なので以下コメント

  # def edit
  #   @mypage_config = MypageConfig.find_by(user_id: current_user.id)
  #   @user = User.find_by(id: current_user.id)

  # end

  # def update
  #   @user = User.find_by(id: current_user.id)
  #   @mypage_config = MypageConfig.find_by(user_id: current_user.id)
  #   @mypage_config.update(mypage_config_params)

  #   if @mypage_config.save
  #     flash[:notice] = "更新しました！"
  #     redirect_to ("/mypage")
  #   else
  #     render action: :edit
  #   end
  # end

  # private
  # def mypage_config_params
  #   params.require(:mypage_config).permit(:items, :introduce, :public, :user_id)
  # end
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/views/mypage/index.html.erb
<h1>Mypage#index</h1>
<h1><%= @user.name%>さんのマイページ</h1>

<h4>mokuからのお知らせ</h4>
　<% @annouce.each do |anouce| %>
    <%= anouce.title%><%= anouce.created_at %>
  <% end %>
<ul>
  <li><%= link_to("MOKUる", new_user_moku_path(@user))%></li>
  <li><%= link_to("MOKUタグ一覧へ", user_moku_type_index_path(@user))%></li>
  <li><%= link_to("成果物一覧へ（王冠から）", user_work_index_path(@user))%></li>
  <li><%= link_to("ブックマーク一覧へ", user_book_marks_path(@user))%></li>
  <li><%= link_to("おしらせ", "/announcements/index" )%></li>
</ul>

<h4>PICK UP<h4>
  <ul>
    <% @work_randoms.each do |work_random| %>
        <li>
        <% work = Work.find_by(id: work_random.id)%>
          <%#= link_to(work_random.title, "users/#{@user.id}/works/#{work.id}/public") %>
          <% if work.user_id == current_user.id%>
            <%= link_to(work_random.title, user_work_path(@user, work)) %>
          <% else %>
            <%= link_to(work_random.title, "/users/#{work.user_id}/works/#{work.id}/public") %>
          <% end %>
        </li>
    <% end %>
  </ul>


<h4>MOKU JUST NOW</h4>
  <ul id="justNowUl"></ul>
  <%= javascript_include_tag "mypage" %>
  <script></script>

<h4><%= "#{@user.name}さんのMOKUアイテム" %></h4>
  <% if @user.items.blank? %>
    <h5>☁︎画面下部の「個人設定」から、使用する道具を登録しよう！</h5>
  <% else %>
    <%= simple_format(@user.items) %>
<% end %>


 <h4>自己紹介</h4>
  <% if @user.introduce.blank? %>
  　<h5>︎︎︎︎☁︎画面下部の「個人設定」から、自己紹介を登録しよう！</h5>
  <% else %>
    <%= simple_format(@user.introduce) %>
<% end %>

<h4><%= "#{@user.name}さんのアカウントは現在#{public_to_s(@user.public)}になっています" %></h4>
<% if @user.admin? %>
<%# booleanを定義している場合、？のメソッドで　tureか？と聞く。
本来聞くメソッドが必ず必要で、今回user.rbに定義はしたんだけど、実は定義しないでもOK
必ず必要だからこそ、もし定義してない場合NoMethodErrorがでて、その時に
booleanのメソッドがないなら生やしてやるよ、とRailsが勝手に判定メソッドをその場で作ってくれるため。
作ってくれるなら書かなくていいよね、という感じでuser.rbのメソッドはコメントアウトした状態。
ちなみにここのif @user.admin?の?は実はあってもなくてもいいけれど、あった方がいいよね、と %>
<h2>管理者メニュー</h2>
  <ul>
    <li>
      <%= link_to("FAQの追加", faqs_new_path )%>
    </li>
    <li>
      <%= link_to("FAQの編集・削除", faqs_path )%>
    </li>
  </ul>
<% end %>

<h1>カレンダー</h1>
<h5><%= link_to("【これまでの全てのMOKU一覧】", user_mokus_path(@user))%></h5>
<%= month_calendar(attribute: :created_at, events: @mokus) do |date, mokus| %>
  <%= date %><br>
  <% mokus.each do |moku| %>
        <%= link_to(moku.moku_type.name, user_moku_path(moku.user_id, moku.id)) %><br>
    <% end %>
<% end %>

app/views/mypage/show.html.erb
<h1>Mypage#show</h1>
<% if @user.public %>
  <h1><%= "成果物の製作者：#{@user.name}さん" %></h1>

  <h4><%= "#{@user.name}さんのMOKUアイテム" %></h4>
    <% if @user.items.blank? %>
      <p><%= "#{@user.name}さんは、MOKUアイテムを登録されていないようです。"%></p>
    <% else %>
      <%= simple_format(@user.items) %>
    <% end %>

  <h4><%= "#{@user.name}さんの自己紹介" %></h4>
    <% if @user.introduce.blank? %>
      <%= "#{@user.name}さんは、自己紹介を登録されていないようです。"%>
    <% else %>
      <%= simple_format(@user.introduce) %>
    <% end %>

<% else %>
  <h3><%= "#{@user.name}さんは非公開ユーザーさんです" %></h3>
<% end %>

<h3><%= link_to("マイページへ戻る", "/mypage")%></h3>